services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sis_network

  app:
    build: .
    depends_on:
      - db
    networks:
      - sis_network

networks:
  sis_network:
    driver: bridge

volumes:
  pgdata:
